name: Build PersonApi

on:
  push:
    branches: [ main ]
  #  paths:
  #  - src/**
  #  - tests/**
env:
  app-name: "cicd-filechecker-fa-qa"
  rg-name: "cicd-qa"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish src/cicdApp.PersonApi/cicdApp.PersonApi.csproj -c Release -o artifacts
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: artifacts
        path: /home/runner/work/cicd/cicd/artifacts/**
        if-no-files-found: error


  deploy_qa:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: QA
      url: ${{ steps.deploywebapp.outputs.webapp-url }}

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: artifacts
        path: artifacts

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.app-name }}
        package: artifacts

    - name: Update config
      uses: Azure/appservice-settings@v1
      with:
       app-name: ${{ env.app-name }}
       slot-name: staging
       app-settings-json: |
         [
             {
                 "name": "UI:Index:Header",
                 "value": "${{ secrets.INDEX_HEADER }}",
                 "slotSetting": true
             }
         ]

    - name: az cli logout
      run: az logout
