name: Build PersonApi

on:
  push:
    branches: [ main ]
  #  paths:
  #  - src/**
  #  - tests/**
env:
  AZURE_FUNCTIONAPP_NAME: cicd-filechecker-fa-qa
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src\cicdApp.PersonApi/publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: src\cicdApp.PersonApi

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: PersonApi
        path: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
        if-no-files-found: error

  deploy_qa:
    needs: build
    runs-on: windows-latest

    environment:
      name: QA
      url: ${{ steps.deploywebapp.outputs.webapp-url }}

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: PersonApi       

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Functions
      id: deploywebapp
      uses: Azure/functions-action@v1.4.4
      with:
        app-name: ${{ env.app-name }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: az cli logout
      run: az logout
